ignores:
  # All type packages are imported implicitly by TypeScript
  - '@types/*'

  # Circle CI
  - depcheck
  - improved-yarn-audit
  - yarn-deduplicate

  # Release process
  - '@metamask/auto-changelog'
  - '@metamask/create-release-branch'

  # Yarn
  - '@lavamoat/allow-scripts'
