version: 2.1

parameters:
  app-dir:
    type: string
    default: packages/app
  common-dir:
    type: string
    default: packages/common
  extension-dir:
    type: string
    default: packages/app/submodules/extension

executors:
  node-browsers:
    docker:
      - image: circleci/node:16-browsers
    environment:
      APP_DIR: << pipeline.parameters.app-dir >>
      COMMON_DIR: << pipeline.parameters.common-dir >>
      EXTENSION_DIR: << pipeline.parameters.extension-dir >>
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    resource_class: large
    environment:
      APP_DIR: << pipeline.parameters.app-dir >>
      COMMON_DIR: << pipeline.parameters.common-dir >>
      EXTENSION_DIR: << pipeline.parameters.extension-dir >>
      NODE_ENV: development

workflows:
  test_and_release:
    jobs:
      - install-deps
      - validate-deps:
          requires:
            - install-deps
      - validate-lock-duplicates:
          requires:
            - install-deps
      - lint-lockfile:
          requires:
            - install-deps
      - validate-lavamoat-config:
          requires:
            - build-common
      - audit:
          requires:
            - install-deps
      - build-common:
          requires:
            - install-deps
      - build-app:
          requires:
            - build-common
      - build-app-test-extension:
          requires:
            - build-common
      - build-app-test-app:
          requires:
            - build-common
      - build-ui:
          requires:
            - install-deps
      - build-ui-test-extension:
          requires:
            - install-deps
      - build-ui-test-app:
          requires:
            - install-deps
      - build-extension-test-extension:
          requires:
            - build-common
      - build-extension-test-app:
          requires:
            - build-common
      - lint-common:
          requires:
            - install-deps
      - lint-app:
          requires:
            - build-common
      - test-unit-common:
          requires:
            - install-deps
      - test-unit-app:
          requires:
            - build-common
      - test-e2e-extension:
          requires:
            - build-app-test-extension
            - build-ui-test-extension
            - build-extension-test-extension
      - test-e2e-extension-snaps:
          requires:
            - build-app-test-extension
            - build-ui-test-extension
            - build-extension-test-extension
      - test-e2e-app:
          requires:
            - build-app-test-app
            - build-ui-test-app
            - build-extension-test-app

jobs:
  install-deps:
    executor: node-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: YARN_CACHE_FOLDER=.yarn_cache yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - .yarn_cache
            - node_modules/
            - << pipeline.parameters.common-dir >>/node_modules/
            - << pipeline.parameters.app-dir >>/node_modules/
            - << pipeline.parameters.extension-dir >>/node_modules/
      - run:
          name: Run root post install
          command: |
            yarn setup:postinstall
      - run:
          name: Run common post install
          command: |
            yarn common setup:postinstall
      - run:
          name: Run extension post install
          command: |
            yarn extension setup:postinstall
      - run:
          name: Run app post install
          command: |
            yarn app setup:postinstall
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - << pipeline.parameters.app-dir >>/node_modules
            - << pipeline.parameters.common-dir >>/node_modules
            - << pipeline.parameters.extension-dir >>/node_modules

  validate-deps:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: root depcheck
          command: yarn depcheck
      - run:
          name: common depcheck
          command: yarn depcheck ${COMMON_DIR}
      - run:
          name: app depcheck
          command: yarn depcheck ${APP_DIR}

  validate-lock-duplicates:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Detect yarn lock deduplications
          command: yarn yarn-deduplicate && git diff --exit-code yarn.lock

  lint-lockfile:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: lockfile-lint
          command: yarn lint:lockfile

  audit:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: yarn audit
          command: .circleci/scripts/yarn-audit.sh

  validate-lavamoat-config:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Validate root allow-scripts config
          command: SCRIPT='allow-scripts' .circleci/scripts/validate-allow-scripts.sh
      - run:
          name: Validate common allow-scripts config
          command: SCRIPT='common allow-scripts' .circleci/scripts/validate-allow-scripts.sh
      - run:
          name: Validate app allow-scripts config
          command: SCRIPT='app allow-scripts' .circleci/scripts/validate-allow-scripts.sh
      - run:
          name: Validate app LavaMoat policy
          command: SCRIPT='app lavamoat' .circleci/scripts/validate-lavamoat-policy.sh
      - run:
          name: Validate UI LavaMoat policy
          command: SCRIPT='app lavamoat:ui' .circleci/scripts/validate-lavamoat-policy.sh

  build-common:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn common build
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.common-dir >>/dist

  build-app:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn app build:app
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${APP_DIR}/dist/app ./${APP_DIR}/dist-app
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.app-dir >>/dist-app

  build-app-test-extension:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn app build:app:test
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${APP_DIR}/dist/app ./${APP_DIR}/dist-app-test-extension
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.app-dir >>/dist-app-test-extension

  build-app-test-app:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn app build:app:test:ui
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${APP_DIR}/dist/app ./${APP_DIR}/dist-app-test-app
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.app-dir >>/dist-app-test-app

  build-ui:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn app build:ui:ci
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${APP_DIR}/dist/ui ./${APP_DIR}/dist-ui
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.app-dir >>/dist-ui

  build-ui-test-extension:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn app dist:desktop:ui
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${APP_DIR}/dist/ui ./${APP_DIR}/dist-ui-test-extension
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.app-dir >>/dist-ui-test-extension

  build-ui-test-app:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn app build:ui:ci
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${APP_DIR}/dist/ui ./${APP_DIR}/dist-ui-test-app
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.app-dir >>/dist-ui-test-app

  build-extension-test-extension:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn extension build:test:desktop
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${EXTENSION_DIR}/dist ./${EXTENSION_DIR}/dist-extension-test
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.extension-dir >>/dist-extension-test

  build-extension-test-app:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn extension build:test:desktop:ui
      - run:
          name: Move dist to avoid conflicts
          command: mv ./${EXTENSION_DIR}/dist ./${EXTENSION_DIR}/dist-extension-test-app
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.extension-dir >>/dist-extension-test-app

  lint-common:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: yarn common lint

  lint-app:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: yarn app lint

  test-unit-common:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: yarn common test
      - store_test_results:
          path: << pipeline.parameters.common-dir >>/test/results/junit.xml

  test-unit-app:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: yarn app test
      - store_test_results:
          path: << pipeline.parameters.app-dir >>/test/results/junit.xml

  test-e2e-extension:
    executor: node-browsers
    parallelism: 8
    steps:
      - checkout
      - run:
          name: Re-Install Chrome
          command: ./.circleci/scripts/chrome-install.sh
      - attach_workspace:
          at: .
      - run:
          name: Move app build
          command: |
            mkdir -p ./${APP_DIR}/dist
            mv ./${APP_DIR}/dist-app-test-extension ./${APP_DIR}/dist/app
      - run:
          name: Move UI build
          command: |
            mv ./${APP_DIR}/dist-ui-test-extension ./${APP_DIR}/dist/ui
      - run:
          name: Move extension build
          command: |
            mv ./${EXTENSION_DIR}/dist-extension-test ./${EXTENSION_DIR}/dist
      - run:
          name: test:e2e:chrome:desktop
          command: |
            if .circleci/scripts/test-run-e2e.sh
            then
              yarn app test:e2e:extension --retries 2
            fi
          no_output_timeout: 20m

  test-e2e-extension-snaps:
    executor: node-browsers
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Re-Install Chrome
          command: ./.circleci/scripts/chrome-install.sh
      - attach_workspace:
          at: .
      - run:
          name: Move app build
          command: |
            mkdir -p ./${APP_DIR}/dist
            mv ./${APP_DIR}/dist-app-test-extension ./${APP_DIR}/dist/app
      - run:
          name: Move UI build
          command: |
            mv ./${APP_DIR}/dist-ui-test-extension ./${APP_DIR}/dist/ui
      - run:
          name: Move extension build
          command: |
            mv ./${EXTENSION_DIR}/dist-extension-test ./${EXTENSION_DIR}/dist
      - run:
          name: test:e2e:chrome:desktop:snaps
          command: |
            if .circleci/scripts/test-run-e2e.sh
            then
              yarn app test:e2e:extension:snaps --retries 2
            fi
          no_output_timeout: 20m

  test-e2e-app:
    executor: playwright
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Move app build
          command: |
            mkdir -p ./${APP_DIR}/dist
            mv ./${APP_DIR}/dist-app-test-app ./${APP_DIR}/dist/app
      - run:
          name: Move UI build
          command: |
            mv ./${APP_DIR}/dist-ui-test-app ./${APP_DIR}/dist/ui
      - run:
          name: Move extension build
          command: |
            mv ./${EXTENSION_DIR}/dist-extension-test-app ./${EXTENSION_DIR}/dist
      - run:
          name: Install PW dependencies
          command: |
            cd ./${APP_DIR}
            npx playwright install chrome
      - run:
          name: Run e2e desktop command
          command: |
            if .circleci/scripts/test-run-e2e.sh
            then
              xvfb-run yarn app test:e2e:app
            fi
          no_output_timeout: 20m
      - store_artifacts:
          name: html-report and artifacts
          path: ./<< pipeline.parameters.app-dir >>/test/playwright/playwright-reports/
      - store_test_results:
          name: report for pipeline integration
          path: ./<< pipeline.parameters.app-dir >>/test/playwright/playwright-reports/junit/test-results.xml
      - store_artifacts:
          name: screenshots and trace.zip
          path: ./<< pipeline.parameters.app-dir >>/test/playwright/test-results/
