ignores:
  # All type packages are imported implicitly by TypeScript
  - '@types/*'

  # Babel
  - '@babel/cli'
  - '@babel/preset-env'
  - '@babel/preset-react'
  - '@babel/preset-typescript'
  
  # tsconfig
  - '@tsconfig/node16'

  # Jest
  - jest-environment-jsdom

  # Electron
  - electron-notarize

  # eslint
  - eslint-config-*.js
  - '@metamask/eslint-config-jest'
  - '@metamask/eslint-config-typescript'

  # Extension Runtime
  - '@babel/runtime'
  - '@download/blockies'
  - '@ensdomains/content-hash'
  - '@eth-optimism/contracts'
  - '@ethereumjs/common'
  - '@formatjs/intl-relativetimeformat'
  - '@fortawesome/fontawesome-free'
  - '@keystonehq/bc-ur-registry-eth'
  - '@keystonehq/metamask-airgapped-keyring'
  - '@material-ui/core'
  - '@metamask/contract-metadata'
  - '@metamask/controllers'
  - '@metamask/design-tokens'
  - '@metamask/eth-json-rpc-infura'
  - '@metamask/eth-ledger-bridge-keyring'
  - '@metamask/eth-token-tracker'
  - '@metamask/etherscan-link'
  - '@metamask/jazzicon'
  - '@metamask/logo'
  - '@metamask/metamask-eth-abis'
  - '@metamask/obs-store'
  - '@metamask/post-message-stream'
  - '@metamask/providers'
  - '@metamask/rpc-methods'
  - '@metamask/slip44'
  - '@metamask/smart-transactions-controller'
  - '@metamask/snap-controllers'
  - '@metamask/snap-utils'
  - '@ngraveio/bc-ur'
  - '@popperjs/core'
  - '@reduxjs/toolkit'
  - '@segment/loosely-validate-event'
  - '@sentry/browser'
  - '@sentry/electron'
  - '@sentry/integrations'
  - '@sentry/types'
  - '@sentry/utils'
  - '@spruceid/siwe-parser'
  - '@truffle/codec'
  - '@truffle/decoder'
  - '@zxing/browser'
  - '@zxing/library'
  - await-semaphore
  - base32-encode
  - base64-js
  - bignumber.js
  - bn.js
  - classnames
  - copy-to-clipboard
  - currency-formatter
  - debounce-stream
  - deep-freeze-strict
  - eth-block-tracker
  - eth-ens-namehash
  - eth-json-rpc-filters
  - eth-json-rpc-middleware
  - eth-keyring-controller
  - eth-method-registry
  - eth-query
  - eth-rpc-errors
  - ethereum-ens-network-map
  - ethereumjs-abi
  - ethereumjs-wallet
  - ethers
  - ethjs
  - ethjs-contract
  - ethjs-query
  - extension-port-stream
  - fast-json-patch
  - fuse.js
  - globalthis
  - human-standard-token-abi
  - immer
  - is-retry-allowed
  - json-rpc-engine
  - json-rpc-middleware-stream
  - jsonschema
  - labeled-stream-splicer
  - localforage
  - lodash
  - luxon
  - nanoid
  - nonce-tracker
  - pify
  - promise-to-callback
  - prop-types
  - pubnub
  - pump
  - punycode
  - qrcode-generator
  - qrcode.react
  - react
  - react-dnd
  - react-dnd-html5-backend
  - react-dom
  - react-idle-timer
  - react-inspector
  - react-otp-input
  - react-popper
  - react-redux
  - react-responsive-carousel
  - react-router-dom
  - react-simple-file-input
  - react-tippy
  - react-toggle-button
  - react-transition-group
  - readable-stream
  - redux
  - redux-persist
  - redux-thunk
  - remove-trailing-slash
  - reselect
  - safe-event-emitter
  - ses
  - single-call-balance-checker-abi
  - swappable-obj-proxy
  - textarea-caret
  - unicode-confusables
  - uuid
  - valid-url
  - web3-stream-provider
  - webextension-polyfill
  - zxcvbn

  # Extension Dev'
  - '@babel/code-frame'
  - '@babel/core'
  - '@babel/eslint-parser'
  - '@babel/eslint-plugin'
  - '@babel/register'
  - '@ethersproject/bignumber'
  - '@lavamoat/lavapack'
  - '@metamask/auto-changelog'
  - '@metamask/eslint-config-mocha'
  - '@metamask/forwarder'
  - '@metamask/phishing-warning'
  - '@metamask/test-dapp'
  - '@sentry/cli'
  - '@storybook/addon-a11y'
  - '@storybook/addon-actions'
  - '@storybook/addon-essentials'
  - '@storybook/addon-knobs'
  - '@storybook/addons'
  - '@storybook/api'
  - '@storybook/client-api'
  - '@storybook/components'
  - '@storybook/core'
  - '@storybook/core-events'
  - '@storybook/react'
  - '@storybook/storybook-deployer'
  - '@storybook/theming'
  - '@testing-library/jest-dom'
  - '@testing-library/react'
  - '@testing-library/react-hooks'
  - '@testing-library/user-event'
  - addons-linter
  - babel-plugin-transform-inline-environment-variables
  - babelify
  - bify-module-groups
  - brfs
  - browser-util-inspect
  - browserify
  - chalk
  - chokidar
  - chromedriver
  - concurrently
  - copy-webpack-plugin
  - cross-spawn
  - css-loader
  - css-to-xpath
  - csstype
  - del
  - depcheck
  - dependency-tree
  - duplexify
  - enzyme
  - enzyme-adapter-react-16
  - eslint-import-resolver-node
  - eslint-import-resolver-typescript
  - eslint-plugin-mocha
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-storybook
  - fancy-log
  - fast-glob
  - fs-extra
  - geckodriver
  - gh-pages
  - globby
  - gulp
  - gulp-autoprefixer
  - gulp-dart-sass
  - gulp-livereload
  - gulp-rename
  - gulp-rtlcss
  - gulp-sort
  - gulp-sourcemaps
  - gulp-stylelint
  - gulp-watch
  - gulp-zip
  - history
  - improved-yarn-audit
  - ini
  - jest-canvas-mock
  - jest-it-up
  - koa
  - lavamoat-browserify
  - lavamoat-viz
  - lockfile-lint
  - loose-envify
  - madge
  - mocha
  - mockttp
  - nock
  - nyc
  - polyfill-crypto.getrandomvalues
  - prettier-plugin-sort-json
  - proxyquire
  - pumpify
  - randomcolor
  - react-devtools
  - read-installed
  - redux-mock-store
  - remote-redux-devtools
  - resolve-url-loader
  - sass
  - sass-loader
  - selenium-webdriver
  - semver
  - serve-handler
  - sinon
  - source-map
  - source-map-explorer
  - squirrelly
  - storybook-dark-mode
  - string.prototype.matchall
  - style-loader
  - stylelint
  - terser
  - through2
  - ts-node
  - ttest
  - vinyl
  - vinyl-buffer
  - vinyl-source-stream
  - vinyl-sourcemaps-apply
  - watchify
  - webpack
  - yargs
  - yarn-deduplicate
