name: "Build and Package"

on: workflow_dispatch

jobs:
  package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install deps
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Run root post install
        shell: bash
        run: yarn setup:postinstall

      - name: Run common post install
        shell: bash
        run: yarn common setup:postinstall

      - name: Run extension post install
        shell: bash
        run: yarn extension setup:postinstall

      - name: Run app post install
        shell: bash
        run: yarn app setup:postinstall

      - name: Build desktop ui
        shell: bash
        run: yarn app build:ui:lavamoat:ci

      - name: Build desktop app
        shell: bash
        run: yarn app build:app
        env:
          INFURA_PROJECT_ID: ${{ INFURA_PROJECT_ID }}

      - name: Package app for ${{ matrix.os }}
        shell: bash
        run:  |
              if [ "$RUNNER_OS" == "Linux" ]; then
                yarn app package:linux:ci -p "never"
              elif [ "$RUNNER_OS" == "Windows" ]; then
                yarn app package:win:ci
              else
                echo "$RUNNER_OS not supported"
                exit 1
              fi
        env:
          WIN_CSC_LINK: ${{ secrets.MMD_WIN_CERT_BASE64 }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.MMD_WIN_CERT_PASSWORD }}
